### ISSUE TITLE
Determine Project Management Tool

### ISSUE THREAD

**Issue by JaJako** [Oeffies/Oeffies#10]
Which Project Management Tool to use. See presentation: [Projekt Management Tool Evaluierung](https://docs.google.com/presentation/d/1g6YsgtGpI4wP5SL2H32dnUdLQ6W_28IzAzcRfzp75bI/edit?usp=share_link)

We (obviously) have chosen GitHub. (Depending on the Time Tracking solution to be chosen we will need this issue to add our times.)

**Comment by JaJako** [comment]
We have chosen GitHub.

**Comment by timvahlbrock** [comment]
@core-team members each needs to add the time spent on this issue.

**Comment by timvahlbrock** [comment]
Time spent: 4 hours

**Comment by JaJako** [comment]
Time spent: 2 hours 30 minutes

**Comment by AconexOfficial** [comment]
Time spent: 2 hours

**Comment by Escowei98** [comment]
Time spent: 2 hours

**Comment by LaraBiss** [comment]
Time spent: 5 hours

**Comment by dkrakau** [comment]
Time spent: 2 hours
